name: Latest blog post workflow
on:
  schedule:
    - cron: '0 0 * * 0' # Runs once a week
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly

jobs:
  update-readme-with-blog:
    name: Fetch latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull in blog articles from feed
        uses: gautamkrishnar/blog-post-workflow@master
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          feed_list: "https://protiumx.github.io/blog/index.xml"
